---
- name: Gather Docker Compose Information
  hosts: all
  tasks:
      - name: Read Docker Compose file
        docker_compose:
            project_src: /opt/cavi2-infrastructure
        register: docker_compose_info
      - name: Store information in variables
        set_fact:
            backend_image: "{{ docker_compose_info.services.backend.image }}"
            investigator_image: "{{ docker_compose_info.services.investigator.image }}"