---
- name: Update Ubuntu OS
  hosts: all
  become: true

  tasks:
      - name: Update package cache
        apt:
            update_cache: yes
        become: true

      - name: Upgrade all packages
        apt:
            autoremove: yes
            autoclean: yes
        become: true
